### PR TITLE
feat: CIEDE2000 & palette optimization by CIEDE2000

### PR DESCRIPTION
**Pull request by cxxxxxn**
CIEDE2000 & palette optimization by difference color difference function
- [x] code
- [x] demo
- [x] doc

### CODE REVIEW

**Review by neoddish — COMMENTED** [review]
confused:

the api `colorDistance` is used to measure the distance btw colors.
'Euclidean' and 'CIEDE2000' are the different measurements.
now colorDistance=Euclidean and CIEDE2000 is another api?

why not:
```
colorDistance({ measure: 'euclidean' })
colorDistance({ measure: 'CIEDE2000' })
colorDistance() // default 'euclidean'
```
'measure' could also be 'type' or sth.

or

```
colorDistance( 'euclidean' )
colorDistance( 'CIEDE2000' )
```

**Comment by cxxxxxn** [comment]
> confused:
> 
> the api `colorDistance` is used to measure the distance btw colors.
> 'Euclidean' and 'CIEDE2000' are the different measurements.
> now colorDistance=Euclidean and CIEDE2000 is another api?
> 
> why not:
> 
> ```
> colorDistance({ measure: 'euclidean' })
> colorDistance({ measure: 'CIEDE2000' })
> colorDistance() // default 'euclidean'
> ```
> 
> 'measure' could also be 'type' or sth.
> 
> or
> 
> ```
> colorDistance( 'euclidean' )
> colorDistance( 'CIEDE2000' )
> ```

I thought color difference and color distance were different, but I just found out that they are defined the same on the wiki, so maybe it would be better to modify it this way

**Comment by cxxxxxn** [comment]
> confused:
> 
> the api `colorDistance` is used to measure the distance btw colors.
> 'Euclidean' and 'CIEDE2000' are the different measurements.
> now colorDistance=Euclidean and CIEDE2000 is another api?
> 
> why not:
> 
> ```
> colorDistance({ measure: 'euclidean' })
> colorDistance({ measure: 'CIEDE2000' })
> colorDistance() // default 'euclidean'
> ```
> 
> 'measure' could also be 'type' or sth.
> 
> or
> 
> ```
> colorDistance( 'euclidean' )
> colorDistance( 'CIEDE2000' )
> ```

Would colorDifference be better? 
There are also measures of color difference like color contrast ratio that sounds different from the color distance.

**Review by neoddish — APPROVED** [review]
lovely

**Comment by neoddish** [comment]
> Would colorDifference be better?
> There are also measures of color difference like color contrast ratio that sounds different from the color distance.

In my opinion, color difference > color distance.

distance is one of differences: you can describe this kind of diff as 'how long'/'how far' in a specific color space.

others like contrast ratio, it's a kind of diff but not distance.

so, I believe colorDistance is more accurate for euclidean and CIEDE2000. but you can also have some api called 'colorDiff', later.

**Comment by neoddish** [comment]
@cxxxxxn If u agree, u can rebase and merge this PR.

**Pull request merged**
