### PR TITLE
fix: more standard naming

### PR DESCRIPTION
**Pull request by cxxxxxn**
rename
getPalette -> getters
professionalTest -> evaluators

### CODE REVIEW

**Comment by neoddish** [comment]
getters -> extractors ？

getter is kind of a reserved word: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by cxxxxxn** [comment]
> getters -> extractors ？
> 
> getter is kind of a reserved word: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

Updated

**Comment by cxxxxxn** [comment]
> getters -> extractors ？
> 
> getter is kind of a reserved word: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

Updated

**Review by neoddish — APPROVED** [review]
LGTM

**Pull request merged**
